<?xml-stylesheet type= "text/xsl" href="Adventurers.xsl"?>
<!-- External DTD -->
<!--DOCTYPE Adventurers SYSTEM "Adventurers.dtd"-->
<!-- Internal DTD -->
<!DOCTYPE Adventurers
[
<!ELEMENT Adventurers (Adventurer)*>
<!ELEMENT Adventurer (Name, from, Profession)*>
<!ELEMENT Name (#PCDATA)*>
<!ATTLIST Name employed CDATA "Yes">
<!ELEMENT from (#PCDATA)*>
<!ATTLIST from native CDATA "No">
<!ELEMENT Profession (#PCDATA)*>
<!ATTLIST Profession techJob CDATA "Yes">
]>

<Adventurers>
	<Adventurer>
		<Name employed="Yes">Abhishek Bajpai</Name>
		<from native="No">California</from>
		<Profession techJob = "No">Aviator</Profession>
	</Adventurer>
	<Adventurer>
		<Name>Abeer Bajpai</Name>
		<from>Spain</from>
		<Profession>Dirt Biker</Profession>
	</Adventurer>
	<Adventurer>
		<Name>Gouri Bajpai</Name>
		<from>Mangolia</from>
		<Profession>UX Researcher</Profession>
	</Adventurer>
	<Adventurer>
		<Name>Amiya Bajpai</Name>
		<from>France</from>
		<Profession>Health Professional</Profession>
	</Adventurer>
	<Adventurer>
		<Name>Everest Bajpai</Name>
		<from>North Pole</from>
		<Profession>Communications Expert</Profession>
	</Adventurer>
	
</Adventurers>